# Generated by Django 4.2.18 on 2025-01-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruyxat',
            name='tell',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
